[repository]
name = "hange-gallery"
managed_by_uv = false
changelog = "CHANGELOG.md"
version = "version.txt"
compose = "docker-compose.yml"

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend]
path = "backend"

[backend.package]
name = "hange.gallery"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend]
path = "frontend"

[frontend.package]
name = "volto-hange-gallery"
path = "frontend/packages/volto-hange-gallery"
changelog = "frontend/packages/volto-hange-gallery/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-hange-gallery/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "96574af4136cae375cc74be36daed12df6ed6f82"
generated_date = "2026-01-11 08:55:18"
